### ISSUE TITLE
Help me in developing a simple app which can send type-0 sms again and again in loop

### ISSUE THREAD

**Issue by mukhlis7** [romankh/gat-app#9]
I want to develop an app which send type-0 sms in iteration. For Example: i wan to send 100 type-0 sms to +933546756321.
This is a very simple app and I have tried to read and modify existing code of GAT-app but failed. I got thousands of errors in Android Studio like 
"error: Import com.android.internal.telephony.gsm.SmsMessage"

**Comment by romankh** [comment]
Did you extract a telephony-common library and add it to your project ? This library contains those classes that can not be found for the imports. See the readme for a brief description

Besides that, if you have a working installation of the app, you can achieve your goal much easier.
Just write a small program in any language, which connects via network and sends the commands of the app's network protocol, in your case you just need to send 

`sms-send#4#0933546756321#0`

over network, in a loop

**Comment by mukhlis7** [comment]
I can't arrange telephony-common library because i didn't find a phone which have Android <=4.2.
Can you provide me that library.
I don't want two apps that do one thing.
And i don't know much about app networks.
If i have that library(and all errors are gone) then nothing is complicated. Then i can develop the app which i am thinking of.
Plz give me that library. It will be a great help.
And i am great fan of your work.

**Comment by romankh** [comment]
I cant provide the library as I dont believe the publication of the library is allowed, it's an internal piece of android

**Comment by mukhlis7** [comment]
Sir, please provide me that library privately i don't want you to publish it. Send me on E-mail or telegram etc. Email: mukhlisg7@gmail.com, (telegram: https://t.me/mukhlis71). And also Android is an open source project.

**Comment by mukhlis7** [comment]
Or how can i use Android source code from (http://androidxref.com/2.3.6/xref/). This repository contain Android source code from 1.6 to 9.0. Sir, Please help me in resolving this issue because i can't find a real device. I have searched all nearby markets.

**Comment by mukhlis7** [comment]
Sir, give me the exact path to put this file. Because i tried these folders but errors are still there 
/gat-app/app
/gat-app/app/src/main/java/at/khassraf/gat/app
/gat-app/app/build/gen/at/khassraf/gat/app
